// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgkswiffobmohovulcdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhna3N3aWZmb2Jtb2hvdnVsY2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzU4MTAsImV4cCI6MjA2MjcxMTgxMH0.6_KNh1KKNgH1dkK74W2WReN5i394m51QNWz0wPRfbwQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);